# Generated by Django 3.2.9 on 2021-12-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='task_cheked',
            field=models.BooleanField(default=0, verbose_name='Задача проверена?'),
        ),
    ]
