# Generated by Django 3.2.9 on 2021-12-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_solution_task_cheked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='name_course',
            field=models.CharField(default=1, max_length=255, verbose_name='Название курса'),
            preserve_default=False,
        ),
    ]
