# Generated by Django 3.2.9 on 2021-12-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211225_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='solution',
            new_name='mark_solution',
        ),
    ]
