# Generated by Django 3.2.9 on 2021-12-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_solution_mark_mark_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='mark_solution',
            new_name='solution',
        ),
    ]
