# Generated by Django 3.2.9 on 2021-12-27 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_mark_solution_mark_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageteacher',
            name='mark_message',
        ),
        migrations.AddField(
            model_name='mark',
            name='text_message_teacher',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение профессора'),
        ),
        migrations.AddField(
            model_name='messageteacher',
            name='message_solution_teachers',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='message_solution_teachers', to='app.solution', verbose_name='Решение_ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MessageStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Текстовое сообщение')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('message_solution_students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_solution_students', to='app.solution', verbose_name='Решение_ID')),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
